var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":229,"id":14868,"methods":[{"el":53,"sc":5,"sl":51},{"el":90,"sc":5,"sl":62},{"el":109,"sc":13,"sl":106},{"el":111,"sc":5,"sl":102},{"el":147,"sc":5,"sl":121},{"el":179,"sc":5,"sl":160},{"el":199,"sc":5,"sl":189},{"el":212,"sc":5,"sl":207},{"el":227,"sc":5,"sl":219}],"name":"ConfigBinder","sl":44}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_113":{"methods":[{"sl":51}],"name":"testNonExistantOption","pass":true,"statements":[{"sl":52}]},"test_115":{"methods":[{"sl":51}],"name":"testRenamesExistingDefaultsFile","pass":true,"statements":[{"sl":52}]},"test_193":{"methods":[{"sl":51}],"name":"testRenamesExistingDefaultsFileWithSuffix","pass":true,"statements":[{"sl":52}]},"test_238":{"methods":[{"sl":51}],"name":"testCreatesDefaultProfile","pass":true,"statements":[{"sl":52}]},"test_303":{"methods":[{"sl":51}],"name":"testExtractsDefaults","pass":true,"statements":[{"sl":52}]},"test_452":{"methods":[{"sl":51}],"name":"testUsesSystemUsernameForProfileNickname","pass":true,"statements":[{"sl":52}]},"test_493":{"methods":[{"sl":51}],"name":"testStats","pass":true,"statements":[{"sl":52}]},"test_563":{"methods":[{"sl":51}],"name":"testDoesNotCreateProfileIfOneExists","pass":true,"statements":[{"sl":52}]},"test_566":{"methods":[{"sl":51}],"name":"testDomainKeyListener","pass":true,"statements":[{"sl":52}]},"test_700":{"methods":[{"sl":51}],"name":"testLoadsVersionIdentity","pass":true,"statements":[{"sl":52}]},"test_701":{"methods":[{"sl":51}],"name":"testAlwaysUpdatesFormatter","pass":true,"statements":[{"sl":52}]},"test_719":{"methods":[{"sl":51}],"name":"testDomainListener","pass":true,"statements":[{"sl":52}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [303, 238, 719, 113, 115, 566, 193, 452, 701, 493, 563, 700], [303, 238, 719, 113, 115, 566, 193, 452, 701, 493, 563, 700], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
