var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":37,"id":14140,"methods":[{"el":35,"sc":5,"sl":32}],"name":"UserErrorEvent","sl":30}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_115":{"methods":[{"sl":32}],"name":"testRenamesExistingDefaultsFile","pass":true,"statements":[{"sl":34}]},"test_116":{"methods":[{"sl":32}],"name":"testOnErrorInfoEmitsUserErrorEvent","pass":true,"statements":[{"sl":34}]},"test_137":{"methods":[{"sl":32}],"name":"testGetUrlPluginWithoutFile","pass":true,"statements":[{"sl":34}]},"test_180":{"methods":[{"sl":32}],"name":"testGetUrlInvalid","pass":true,"statements":[{"sl":34}]},"test_193":{"methods":[{"sl":32}],"name":"testRenamesExistingDefaultsFileWithSuffix","pass":true,"statements":[{"sl":34}]},"test_238":{"methods":[{"sl":32}],"name":"testCreatesDefaultProfile","pass":true,"statements":[{"sl":34}]},"test_250":{"methods":[{"sl":32}],"name":"testGetUrlForJarFileInvalud","pass":true,"statements":[{"sl":34}]},"test_274":{"methods":[{"sl":32}],"name":"testGetUrlZipWithoutFile","pass":true,"statements":[{"sl":34}]},"test_303":{"methods":[{"sl":32}],"name":"testExtractsDefaults","pass":true,"statements":[{"sl":34}]},"test_382":{"methods":[{"sl":32}],"name":"testGetColourOOB","pass":true,"statements":[{"sl":34}]},"test_452":{"methods":[{"sl":32}],"name":"testUsesSystemUsernameForProfileNickname","pass":true,"statements":[{"sl":34}]},"test_473":{"methods":[{"sl":32}],"name":"testGetColourHexInvalid","pass":true,"statements":[{"sl":34}]},"test_563":{"methods":[{"sl":32}],"name":"testDoesNotCreateProfileIfOneExists","pass":true,"statements":[{"sl":34}]},"test_686":{"methods":[{"sl":32}],"name":"testGetUrlHTTPInvalid","pass":true,"statements":[{"sl":34}]},"test_691":{"methods":[{"sl":32}],"name":"testGetUrlThemeWithoutFile","pass":true,"statements":[{"sl":34}]},"test_700":{"methods":[{"sl":32}],"name":"testLoadsVersionIdentity","pass":true,"statements":[{"sl":34}]},"test_701":{"methods":[{"sl":32}],"name":"testAlwaysUpdatesFormatter","pass":true,"statements":[{"sl":34}]},"test_712":{"methods":[{"sl":32}],"name":"testGetUrlJarWithoutFile","pass":true,"statements":[{"sl":34}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [686, 250, 303, 238, 137, 382, 712, 701, 180, 563, 700, 116, 115, 193, 452, 473, 274, 691], [], [686, 250, 303, 238, 137, 382, 712, 701, 180, 563, 700, 116, 115, 193, 452, 473, 274, 691], [], [], []]
