var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":52,"id":3185,"methods":[{"el":40,"sc":5,"sl":38},{"el":50,"sc":5,"sl":48}],"name":"InvalidURIException","sl":28}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_183":{"methods":[{"sl":48}],"name":"testURIEmptyPort","pass":true,"statements":[{"sl":49}]},"test_218":{"methods":[{"sl":48}],"name":"testTextInvalidHostname","pass":true,"statements":[{"sl":49}]},"test_254":{"methods":[{"sl":48}],"name":"testInvalidPort","pass":true,"statements":[{"sl":49}]},"test_278":{"methods":[{"sl":48}],"name":"testOutOfRangePort2","pass":true,"statements":[{"sl":49}]},"test_285":{"methods":[{"sl":48}],"name":"testOutOfRangePort2","pass":true,"statements":[{"sl":49}]},"test_291":{"methods":[{"sl":38}],"name":"testURIInvalidUserInfo","pass":true,"statements":[{"sl":39}]},"test_324":{"methods":[{"sl":38}],"name":"testTextEmptyPort","pass":true,"statements":[{"sl":39}]},"test_333":{"methods":[{"sl":48}],"name":"testTextInvalidPort","pass":true,"statements":[{"sl":49}]},"test_35":{"methods":[{"sl":48}],"name":"testOutOfRangePort1","pass":true,"statements":[{"sl":49}]},"test_38":{"methods":[{"sl":38}],"name":"testURIInvalidPort","pass":true,"statements":[{"sl":39}]},"test_458":{"methods":[{"sl":48}],"name":"testTextPortOutOfRange","pass":true,"statements":[{"sl":49}]},"test_46":{"methods":[{"sl":48}],"name":"testURINotIntPort","pass":true,"statements":[{"sl":49}]},"test_496":{"methods":[{"sl":48}],"name":"testOutOfRangePort1","pass":true,"statements":[{"sl":49}]},"test_538":{"methods":[{"sl":38}],"name":"testURINoScheme","pass":true,"statements":[{"sl":39}]},"test_564":{"methods":[{"sl":48}],"name":"testURIPortOutOfRange","pass":true,"statements":[{"sl":49}]},"test_569":{"methods":[{"sl":48}],"name":"testURIInvalidHostname","pass":true,"statements":[{"sl":49}]},"test_593":{"methods":[{"sl":38}],"name":"testURINoAuthority","pass":true,"statements":[{"sl":39}]},"test_632":{"methods":[{"sl":48}],"name":"testInvalidPort","pass":true,"statements":[{"sl":49}]},"test_70":{"methods":[{"sl":48}],"name":"testTextNotIntPort","pass":true,"statements":[{"sl":49}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [538, 38, 291, 593, 324], [538, 38, 291, 593, 324], [], [], [], [], [], [], [], [], [458, 564, 218, 254, 569, 70, 285, 632, 46, 35, 183, 333, 496, 278], [458, 564, 218, 254, 569, 70, 285, 632, 46, 35, 183, 333, 496, 278], [], [], []]
