var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":67,"id":9939,"methods":[{"el":40,"sc":5,"sl":38},{"el":44,"sc":5,"sl":42},{"el":48,"sc":5,"sl":46},{"el":53,"sc":5,"sl":50},{"el":65,"sc":5,"sl":55}],"name":"PreviousCommand","sl":31}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_154":{"methods":[{"sl":38},{"sl":42},{"sl":46},{"sl":55}],"name":"testGetCommandTime","pass":true,"statements":[{"sl":39},{"sl":43},{"sl":47},{"sl":57},{"sl":60},{"sl":63},{"sl":64}]},"test_162":{"methods":[{"sl":38}],"name":"testParseCommandWithoutArguments","pass":true,"statements":[{"sl":39}]},"test_215":{"methods":[{"sl":38}],"name":"testParseSilencedChannelCommandWithoutArguments","pass":true,"statements":[{"sl":39}]},"test_27":{"methods":[{"sl":38}],"name":"testParseChannelCommandWithoutArguments","pass":true,"statements":[{"sl":39}]},"test_495":{"methods":[{"sl":38}],"name":"testParseSilentCommandWithArguments","pass":true,"statements":[{"sl":39}]},"test_526":{"methods":[{"sl":38}],"name":"testParseChannelCommandWithArguments","pass":true,"statements":[{"sl":39}]},"test_545":{"methods":[{"sl":38}],"name":"testParseSilentCommandWithoutArguments","pass":true,"statements":[{"sl":39}]},"test_622":{"methods":[{"sl":38}],"name":"testParseCommandWithArguments","pass":true,"statements":[{"sl":39}]},"test_706":{"methods":[{"sl":38}],"name":"testParseSilencedChannelCommandWithArguments","pass":true,"statements":[{"sl":39}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [162, 495, 27, 622, 706, 154, 545, 526, 215], [162, 495, 27, 622, 706, 154, 545, 526, 215], [], [], [154], [154], [], [], [154], [154], [], [], [], [], [], [], [], [154], [], [154], [], [], [154], [], [], [154], [154], [], [], []]
