var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":115,"id":5308,"methods":[{"el":54,"sc":5,"sl":44},{"el":61,"sc":5,"sl":56},{"el":113,"sc":5,"sl":63}],"name":"IntelligentLinkingTest","sl":39}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_109":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_128":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_134":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_176":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_187":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_192":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_214":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_227":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_245":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_290":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_330":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_389":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_423":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_431":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_472":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_511":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_534":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_592":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_620":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_621":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_674":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_83":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]},"test_95":{"methods":[{"sl":56}],"name":"testLink","pass":true,"statements":[{"sl":58}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [245, 95, 176, 423, 431, 592, 674, 472, 214, 187, 290, 330, 534, 128, 192, 109, 227, 621, 620, 389, 83, 134, 511], [], [245, 95, 176, 423, 431, 592, 674, 472, 214, 187, 290, 330, 534, 128, 192, 109, 227, 621, 620, 389, 83, 134, 511], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
